# Generated by Django 3.2.5 on 2021-11-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='Fecha de lanzamiento')),
                ('cover_page', models.ImageField(upload_to='portadas', verbose_name='Imagen de portada')),
                ('visits', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('N', 'Novela'), ('R', 'Realismo magico'), ('B', 'Biografia'), ('H', 'Historica'), ('C', 'Ciencia ficcion'), ('D', 'Detectivesca'), ('T', 'Terror'), ('S', 'Satira')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
