# Generated by Django 3.2.5 on 2021-11-26 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0003_auto_20211126_1554'),
        ('libro', '0002_auto_20211126_1554'),
        ('autor', '0003_auto_20211126_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.AddField(
            model_name='book',
            name='Authors',
            field=models.ManyToManyField(to='autor.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_libro', to='libro.category'),
        ),
    ]
