# Generated by Django 3.2.5 on 2021-11-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20211126_1554'),
        ('autor', '0002_auto_20211126_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='nombre',
            new_name='name',
        ),
    ]
